[package]
name = "puzzles"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
fancy-regex = "0.14.0"
itertools = "0.14.0"
md-5 = "0.10.6"
reqwest = { version = "0.12", features = ["blocking"] }
rustc-hash = "2.1.0"
